### ISSUE TITLE
Collection contains invalid files

### ISSUE THREAD

**Issue by ssbarnea** [ansible-collections/community.sops#111]
It seems that this collection contains problems like invalid characters inside YAML files, such `collections/ansible_collections/community/sops/tests/integration/targets/filter_decrypt/files/hidden-json.yaml` which contains tabs, something YAML specification explicitly forbids.

This is identified by both ansible-lint and yamllint tools.

I would advise configuring this and running ansible-lint as a github action, especially as in the near future, upload to galaxy will be rejected if violations are found.

Optionally you could also consider removing the test files from the archive, see https://github.com/ansible-community/community-topics/issues/126

**Comment by felixfontein** [comment]
Please note that the main tool for checking Ansible collections is ansible-test, and these files are correctly added to its ignore files (see for example https://github.com/ansible-collections/community.sops/blob/main/tests/sanity/ignore-2.14.txt).

These files are intentionally not YAML files, so there's no reason to change them. If Galaxy rejects such collections in the future, that's a bug in Galaxy that should be fixed.

**Comment by cidrblock** [comment]
ansible-lint is part of the suite of tools that the ansible community uses to improve and write content. In order to test ansible-lint and ensure it work broadly and well for everyone, periodically it is run against community collections for rule feedback and performance testing reasons. 

ansible-lint is also tightly integrated into the VS code extension and ansible-navigator as well.

TY @ssbarnea for bringing attention to this, although I understand ansible-test sanity is the bar for galaxy, I think it is important we continue to bring visibility to opportunities for improvement across all the collections.

**Comment by felixfontein** [comment]
@cidrblock ansible-test is the main tool used by the community to lint collections. If ansible-lint wants to step up as a collection linter, it would be helpful if it would use ansible-test's ignore files to avoid unnecessary false positives, if there is no global way to ignore such errors that works for both ansible-test and other tools like ansible-lint. Collections that have tests sometimes need to include "broken" / "invalid" files for testing purposes, I don't see why a collection should be rejected because it contains such files, especially when these are in tests/.

**Comment by cidrblock** [comment]
@felixfontein a brilliant suggestion :)  will look into it.
